create table SUPLIDORES (
    ID INT,
    NOMBRE VARCHAR(50),
    TELEFONO VARCHAR(50),
    DIRECCION VARCHAR(50)
);
insert into SUPLIDORES (ID, NOMBRE, TELEFONO, DIRECCION) values (1, 'Kwilith', '910-975-4651', '9441 Bluejay Alley');
insert into SUPLIDORES (ID, NOMBRE, TELEFONO, DIRECCION) values (2, 'Tagfeed', '341-716-7580', '67 Grayhawk Plaza');
insert into SUPLIDORES (ID, NOMBRE, TELEFONO, DIRECCION) values (3, 'Skilith', '757-284-2694', '71172 Oakridge Circle');
insert into SUPLIDORES (ID, NOMBRE, TELEFONO, DIRECCION) values (4, 'Bluezoom', '208-795-1466', '5 Trailsway Park');
insert into SUPLIDORES (ID, NOMBRE, TELEFONO, DIRECCION) values (5, 'Avaveo', '376-472-9350', '67955 Reindahl Point');
insert into SUPLIDORES (ID, NOMBRE, TELEFONO, DIRECCION) values (6, 'Zoomcast', '357-410-6796', '46 Sherman Parkway');
insert into SUPLIDORES (ID, NOMBRE, TELEFONO, DIRECCION) values (7, 'Devbug', '298-252-2039', '3 David Trail');

DECLARE @TOTAL INT = (SELECT COUNT (*) FROM ARTICULOS)
PRINT @TOTAL
SELECT
	SUPLIDOR_ID,
	S.NOMBRE,
	COUNT (*) AS CANTIDAD,
	CONCAT((CAST(COUNT(*) AS FLOAT) / @TOTAL)*100, '%') AS PORCENTAJE
FROM ARTICULOS A
FULL JOIN SUPLIDORES S ON S.ID = A.SUPLIDOR_ID
--WHERE STOCK > 0
GROUP BY SUPLIDOR_ID ,S.NOMBRE

UPDATE ARTICULOS
SET STOCK = 0
WHERE ID IN (
    SELECT TOP 100 ID
    FROM ARTICULOS
    ORDER BY NEWID()
);

--Seleccionar los artículos con sus proveedores:
SELECT ARTICULOS.*, SUPLIDORES.NOMBRE AS PROVEEDOR
FROM ARTICULOS
LEFT JOIN SUPLIDORES ON ARTICULOS.SUPLIDOR_ID = SUPLIDORES.ID;

--Contar el número de artículos suministrados por cada proveedor:
SELECT SUPLIDORES.NOMBRE AS PROVEEDOR, COUNT(ARTICULOS.ID) AS NUMERO_DE_ARTICULOS
FROM SUPLIDORES
LEFT JOIN ARTICULOS ON SUPLIDORES.ID = ARTICULOS.SUPLIDOR_ID
GROUP BY SUPLIDORES.NOMBRE;

--Listar los proveedores con sus artículos en stock:
SELECT SUPLIDORES.NOMBRE AS PROVEEDOR, ARTICULOS.*
FROM SUPLIDORES
INNER JOIN ARTICULOS ON SUPLIDORES.ID = ARTICULOS.SUPLIDOR_ID
WHERE ARTICULOS.STOCK > 0;
